export type VehicleType = "VHC Exploit" | "VHC Admin" | "Machines";
export type RateUnit = "mois" | "jours" | "";

export interface Vehicle {
  id: string;
  type: VehicleType;
  brand: string;
  plate: string | null;
  year: number;
  notes: string;
  lastExpertise: string | null;   // ISO date string YYYY-MM-DD
  lastService: string | null;     // ISO date string YYYY-MM-DD
  purchasePrice: number;
  company: string;
  billedToMBAS: number;           // Facturé à MBA S
  leasingMonthly: number;         // Monthly leasing payment
  leasingNumber: string | null;
  leasingEnd: string | null;      // ISO date string YYYY-MM-DD
  insuranceMonthly: number;
  resaleMonthly: number;
  refacturingRate: number;
  refacturingUnit: RateUnit;
  refacturingTo: string;
}

export const TODAY_VHC = new Date("2026-03-27");

export function isLeasingExpired(v: Vehicle): boolean {
  if (!v.leasingEnd || v.leasingMonthly <= 0) return false;
  return new Date(v.leasingEnd) < TODAY_VHC;
}

export function isLeasingEndingSoon(v: Vehicle): boolean {
  if (!v.leasingEnd || v.leasingMonthly <= 0) return false;
  const end = new Date(v.leasingEnd);
  if (end < TODAY_VHC) return false;
  const sixMonthsFromNow = new Date(TODAY_VHC);
  sixMonthsFromNow.setMonth(sixMonthsFromNow.getMonth() + 6);
  return end <= sixMonthsFromNow;
}

export function needsExpertise(v: Vehicle): boolean {
  if (!v.lastExpertise) return false;
  const exp = new Date(v.lastExpertise);
  const twoYearsAgo = new Date(TODAY_VHC);
  twoYearsAgo.setFullYear(twoYearsAgo.getFullYear() - 2);
  return exp < twoYearsAgo;
}

export function formatCHF(n: number): string {
  if (n === 0) return "CHF 0.–";
  return new Intl.NumberFormat("fr-CH", {
    style: "currency",
    currency: "CHF",
    minimumFractionDigits: 0,
    maximumFractionDigits: 2,
  }).format(n);
}

export function formatDate(d: string): string {
  return new Date(d).toLocaleDateString("fr-CH", {
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
  });
}

export const vehicles: Vehicle[] = [
  // ── VHC Exploit ──────────────────────────────────────────────────────────────
  {
    id: "I48",
    type: "VHC Exploit",
    brand: "IVECO Daily",
    plate: "VS 336 406",
    year: 2019,
    notes: "",
    lastExpertise: "2025-07-31",
    lastService: null,
    purchasePrice: 52773,
    company: "MBA Construction",
    billedToMBAS: 0,
    leasingMonthly: 0,
    leasingNumber: null,
    leasingEnd: null,
    insuranceMonthly: 82.23,
    resaleMonthly: 86.34,
    refacturingRate: 1400,
    refacturingUnit: "mois",
    refacturingTo: "MBA + essence",
  },
  {
    id: "I55",
    type: "VHC Exploit",
    brand: "IVECO Daily",
    plate: "VS 217 511",
    year: 2020,
    notes: "service: 28.11.25 / rempl commande embrayage: 12.25",
    lastExpertise: "2025-11-06",
    lastService: "2025-11-06",
    purchasePrice: 54927,
    company: "MBA Construction",
    billedToMBAS: 0,
    leasingMonthly: 0,
    leasingNumber: null,
    leasingEnd: null,
    insuranceMonthly: 82.87,
    resaleMonthly: 87.01,
    refacturingRate: 1400,
    refacturingUnit: "mois",
    refacturingTo: "MBA + essence",
  },
  {
    id: "I49",
    type: "VHC Exploit",
    brand: "IVECO Daily",
    plate: "VS 321 354",
    year: 2023,
    notes: "Nouveau vhc après dégât total",
    lastExpertise: null,
    lastService: null,
    purchasePrice: 53850,
    company: "MBA Construction",
    billedToMBAS: 0,
    leasingMonthly: 875.60,
    leasingNumber: "85117-2002 / Raiff",
    leasingEnd: "2027-03-31",
    insuranceMonthly: 82.53,
    resaleMonthly: 1006.04,
    refacturingRate: 1400,
    refacturingUnit: "mois",
    refacturingTo: "MBA + essence",
  },
  {
    id: "I25",
    type: "VHC Exploit",
    brand: "IVECO Daily",
    plate: "VS 323 314",
    year: 2020,
    notes: "contrôle pr expertise niveaux, freins, feux, pneus: 12.25",
    lastExpertise: "2025-11-17",
    lastService: "2025-11-17",
    purchasePrice: 54927,
    company: "MBA Construction",
    billedToMBAS: 0,
    leasingMonthly: 0,
    leasingNumber: null,
    leasingEnd: null,
    insuranceMonthly: 82.98,
    resaleMonthly: 87.13,
    refacturingRate: 1400,
    refacturingUnit: "mois",
    refacturingTo: "MBA + essence",
  },
  {
    id: "I44",
    type: "VHC Exploit",
    brand: "IVECO Daily",
    plate: "VS 348 787",
    year: 2018,
    notes: "service 22.10.25 - niveaux, pression circuit eau, remplacement tuyau chauffage",
    lastExpertise: "2023-08-04",
    lastService: null,
    purchasePrice: 49542,
    company: "MBA Construction",
    billedToMBAS: 0,
    leasingMonthly: 0,
    leasingNumber: null,
    leasingEnd: null,
    insuranceMonthly: 80.90,
    resaleMonthly: 84.95,
    refacturingRate: 1400,
    refacturingUnit: "mois",
    refacturingTo: "MBA + essence",
  },
  {
    id: "I45",
    type: "VHC Exploit",
    brand: "IVECO Daily",
    plate: "VS 470 581",
    year: 2019,
    notes: "gros service décembre 2025: vidange, purge freins, filtres",
    lastExpertise: "2023-08-07",
    lastService: null,
    purchasePrice: 52773,
    company: "MBA Construction",
    billedToMBAS: 0,
    leasingMonthly: 0,
    leasingNumber: null,
    leasingEnd: null,
    insuranceMonthly: 84.06,
    resaleMonthly: 88.26,
    refacturingRate: 1400,
    refacturingUnit: "mois",
    refacturingTo: "MBA + essence",
  },
  {
    id: "I27",
    type: "VHC Exploit",
    brand: "IVECO Daily",
    plate: "VS 578 727",
    year: 2018,
    notes: "Plaques VS 424 383 annulées 22.05.2024",
    lastExpertise: "2025-07-29",
    lastService: null,
    purchasePrice: 53526,
    company: "MBA Construction",
    billedToMBAS: 0,
    leasingMonthly: 0,
    leasingNumber: null,
    leasingEnd: null,
    insuranceMonthly: 82.23,
    resaleMonthly: 86.34,
    refacturingRate: 1400,
    refacturingUnit: "mois",
    refacturingTo: "MBA + essence",
  },
  {
    id: "I41",
    type: "VHC Exploit",
    brand: "IVECO Daily",
    plate: "VS 241 842",
    year: 2018,
    notes: "Remplacement disque + plaquettes freins 10.11.2025",
    lastExpertise: "2022-12-29",
    lastService: null,
    purchasePrice: 49542,
    company: "MBA Construction",
    billedToMBAS: 0,
    leasingMonthly: 0,
    leasingNumber: null,
    leasingEnd: null,
    insuranceMonthly: 80.90,
    resaleMonthly: 84.95,
    refacturingRate: 1400,
    refacturingUnit: "mois",
    refacturingTo: "MBA + essence",
  },
  {
    id: "TALENTO-510931",
    type: "VHC Exploit",
    brand: "Fiat Talento 2.0 dCi",
    plate: "VS 510 931",
    year: 2020,
    notes: "contrôle periodique 01.12.2025: rempl. plaquettes freins, filtres, huile",
    lastExpertise: "2023-06-07",
    lastService: "2025-12-01",
    purchasePrice: 23306,
    company: "MBA Construction",
    billedToMBAS: 0,
    leasingMonthly: 0,
    leasingNumber: null,
    leasingEnd: null,
    insuranceMonthly: 63.26,
    resaleMonthly: 66.42,
    refacturingRate: 770,
    refacturingUnit: "mois",
    refacturingTo: "MBA + éventuelles factures",
  },
  {
    id: "FOURGON-1",
    type: "VHC Exploit",
    brand: "Iveco 35S18 Daily (Fourgon 1)",
    plate: "VS 409 624",
    year: 2022,
    notes: "Nouveau vhc remplacé 2022",
    lastExpertise: "2025-10-10",
    lastService: null,
    purchasePrice: 48465,
    company: "MBA Services",
    billedToMBAS: 3816.05,
    leasingMonthly: 0,
    leasingNumber: null,
    leasingEnd: null,
    insuranceMonthly: 82.95,
    resaleMonthly: 87.10,
    refacturingRate: 1400,
    refacturingUnit: "mois",
    refacturingTo: "ASV Fenêtres et Portes + essence",
  },
  {
    id: "TALENTO-470581",
    type: "VHC Exploit",
    brand: "Fiat Talento 1.6 dCi",
    plate: "VS 470 581",
    year: 2017,
    notes: "",
    lastExpertise: "2022-08-18",
    lastService: null,
    purchasePrice: 23000,
    company: "MBA Construction",
    billedToMBAS: 7016,
    leasingMonthly: 0,
    leasingNumber: null,
    leasingEnd: null,
    insuranceMonthly: 65.76,
    resaleMonthly: 69.05,
    refacturingRate: 750,
    refacturingUnit: "mois",
    refacturingTo: "MBA Construction",
  },
  {
    id: "TALENTO-475959",
    type: "VHC Exploit",
    brand: "Fiat Talento 1.6 dCi",
    plate: "VS 475 959",
    year: 2018,
    notes: "12.25: contrôle freins, feux, pression pneus, Ad-Blue",
    lastExpertise: "2024-01-04",
    lastService: null,
    purchasePrice: 23694,
    company: "MBA Construction",
    billedToMBAS: 8464,
    leasingMonthly: 0,
    leasingNumber: null,
    leasingEnd: null,
    insuranceMonthly: 66.03,
    resaleMonthly: 69.34,
    refacturingRate: 750,
    refacturingUnit: "mois",
    refacturingTo: "ASV Color",
  },
  {
    id: "REM-259957",
    type: "VHC Exploit",
    brand: "Remorque Boeckmann",
    plate: "VS 259 957",
    year: 2016,
    notes: "",
    lastExpertise: "2026-01-28",
    lastService: null,
    purchasePrice: 5500,
    company: "MBA Construction",
    billedToMBAS: 0,
    leasingMonthly: 0,
    leasingNumber: null,
    leasingEnd: null,
    insuranceMonthly: 0,
    resaleMonthly: 0,
    refacturingRate: 150,
    refacturingUnit: "mois",
    refacturingTo: "MBA",
  },
  {
    id: "REM-253242",
    type: "VHC Exploit",
    brand: "Remorque Hulco Terrax-2",
    plate: "VS 253 242",
    year: 2018,
    notes: "",
    lastExpertise: null,
    lastService: null,
    purchasePrice: 5923,
    company: "MBA Construction",
    billedToMBAS: 0,
    leasingMonthly: 0,
    leasingNumber: null,
    leasingEnd: null,
    insuranceMonthly: 0,
    resaleMonthly: 0,
    refacturingRate: 150,
    refacturingUnit: "mois",
    refacturingTo: "MBA",
  },
  {
    id: "REM-253241",
    type: "VHC Exploit",
    brand: "Remorque Anssems PSX",
    plate: "VS 253 241",
    year: 2018,
    notes: "",
    lastExpertise: null,
    lastService: null,
    purchasePrice: 5577,
    company: "MBA Construction",
    billedToMBAS: 0,
    leasingMonthly: 0,
    leasingNumber: null,
    leasingEnd: null,
    insuranceMonthly: 0,
    resaleMonthly: 0,
    refacturingRate: 150,
    refacturingUnit: "mois",
    refacturingTo: "MBA",
  },
  {
    id: "REM-262565",
    type: "VHC Exploit",
    brand: "Remorque Hulco Terrax-2",
    plate: "VS 262 565",
    year: 2017,
    notes: "",
    lastExpertise: null,
    lastService: null,
    purchasePrice: 5940,
    company: "MBA Construction",
    billedToMBAS: 0,
    leasingMonthly: 0,
    leasingNumber: null,
    leasingEnd: null,
    insuranceMonthly: 0,
    resaleMonthly: 0,
    refacturingRate: 150,
    refacturingUnit: "mois",
    refacturingTo: "MBA",
  },
  {
    id: "REM-275954",
    type: "VHC Exploit",
    brand: "Remorque Agados",
    plate: "VS 275 954",
    year: 2009,
    notes: "",
    lastExpertise: null,
    lastService: null,
    purchasePrice: 0,
    company: "MBA Construction",
    billedToMBAS: 0,
    leasingMonthly: 0,
    leasingNumber: null,
    leasingEnd: null,
    insuranceMonthly: 0,
    resaleMonthly: 0,
    refacturingRate: 100,
    refacturingUnit: "mois",
    refacturingTo: "ASV Fenêtres et Portes",
  },
  {
    id: "REM-250178",
    type: "VHC Exploit",
    brand: "Remorque PSX3000",
    plate: "VS 250 178",
    year: 2017,
    notes: "",
    lastExpertise: null,
    lastService: null,
    purchasePrice: 4320,
    company: "ASV EG",
    billedToMBAS: 0,
    leasingMonthly: 0,
    leasingNumber: null,
    leasingEnd: null,
    insuranceMonthly: 0,
    resaleMonthly: 0,
    refacturingRate: 150,
    refacturingUnit: "mois",
    refacturingTo: "ASV Fenêtres et Portes",
  },
  {
    id: "REM-263924",
    type: "VHC Exploit",
    brand: "Remorque Niewiadow Blyss K350",
    plate: "VS 263 924",
    year: 2019,
    notes: "",
    lastExpertise: null,
    lastService: null,
    purchasePrice: 13000,
    company: "MBA Services",
    billedToMBAS: 0,
    leasingMonthly: 0,
    leasingNumber: null,
    leasingEnd: null,
    insuranceMonthly: 0,
    resaleMonthly: 0,
    refacturingRate: 0,
    refacturingUnit: "",
    refacturingTo: "",
  },
  {
    id: "FOURGON-2",
    type: "VHC Exploit",
    brand: "Iveco 35C18 Daily (Fourgon 2)",
    plate: "VS 472 745",
    year: 2023,
    notes: "Reprise ancien Fourgon / plaquettes: 12.25",
    lastExpertise: null,
    lastService: null,
    purchasePrice: 61389,
    company: "MBA Services",
    billedToMBAS: 0,
    leasingMonthly: 1308.50,
    leasingNumber: "5001264 / ZH",
    leasingEnd: "2026-10-31",
    insuranceMonthly: 85.71,
    resaleMonthly: 1463.92,
    refacturingRate: 1400,
    refacturingUnit: "mois",
    refacturingTo: "ASV Fenêtres et Portes + essence",
  },
  {
    id: "FOURGON-3",
    type: "VHC Exploit",
    brand: "Iveco 35S18 Daily (Fourgon 3)",
    plate: "VS 557 272",
    year: 2023,
    notes: "",
    lastExpertise: null,
    lastService: null,
    purchasePrice: 49000,
    company: "MBA Services",
    billedToMBAS: 0,
    leasingMonthly: 1047.50,
    leasingNumber: "85117-2001 / Raiff",
    leasingEnd: "2026-05-31",
    insuranceMonthly: 86.02,
    resaleMonthly: 1190.19,
    refacturingRate: 1400,
    refacturingUnit: "mois",
    refacturingTo: "ASV Fenêtres et Portes + essence",
  },

  // ── VHC Admin ─────────────────────────────────────────────────────────────────
  {
    id: "TUCSON-BLANCHE",
    type: "VHC Admin",
    brand: "Hyundai Tucson (Blanche)",
    plate: "VS 224 612",
    year: 2021,
    notes: "",
    lastExpertise: "2025-07-31",
    lastService: null,
    purchasePrice: 39300,
    company: "MBA Services",
    billedToMBAS: 0,
    leasingMonthly: 0,
    leasingNumber: null,
    leasingEnd: null,
    insuranceMonthly: 84.33,
    resaleMonthly: 88.54,
    refacturingRate: 0,
    refacturingUnit: "",
    refacturingTo: "",
  },
  {
    id: "TUCSON-GRISE",
    type: "VHC Admin",
    brand: "Hyundai Tucson (Grise)",
    plate: "VS 588 730",
    year: 2024,
    notes: "",
    lastExpertise: "2025-07-31",
    lastService: null,
    purchasePrice: 45200,
    company: "MBA Services",
    billedToMBAS: 0,
    leasingMonthly: 983.40,
    leasingNumber: "5001899712 / Alphera",
    leasingEnd: "2028-03-31",
    insuranceMonthly: 0,
    resaleMonthly: 1032.57,
    refacturingRate: 0,
    refacturingUnit: "",
    refacturingTo: "",
  },
  {
    id: "TESLA-RAPHAEL",
    type: "VHC Admin",
    brand: "TESLA Perf — Raphaël",
    plate: "VS 545 176",
    year: 2022,
    notes: "",
    lastExpertise: null,
    lastService: null,
    purchasePrice: 64180,
    company: "MBA Services",
    billedToMBAS: 0,
    leasingMonthly: 1151.55,
    leasingNumber: "RN117540529 / Leaseteq",
    leasingEnd: "2026-08-31",
    insuranceMonthly: 74.99,
    resaleMonthly: 1287.87,
    refacturingRate: 1250,
    refacturingUnit: "mois",
    refacturingTo: "MBA Immobilier SA",
  },
  {
    id: "ALFA-GIOVANNI",
    type: "VHC Admin",
    brand: "Alfa Roméo Giulia — Giovanni",
    plate: "VS 33339",
    year: 2025,
    notes: "Reprise Maserati Levante -45'000",
    lastExpertise: null,
    lastService: null,
    purchasePrice: 128500,
    company: "MBA Services",
    billedToMBAS: 0,
    leasingMonthly: 1266.80,
    leasingNumber: "9000000890326",
    leasingEnd: "2029-10-31",
    insuranceMonthly: 0,
    resaleMonthly: 1330.14,
    refacturingRate: 0,
    refacturingUnit: "",
    refacturingTo: "MBA Immobilier SA + autres",
  },
  {
    id: "AUDI-Q5",
    type: "VHC Admin",
    brand: "Audi Q5",
    plate: "VS 502 419",
    year: 2019,
    notes: "",
    lastExpertise: null,
    lastService: null,
    purchasePrice: 70790,
    company: "MBA Construction",
    billedToMBAS: 0,
    leasingMonthly: 0,
    leasingNumber: null,
    leasingEnd: null,
    insuranceMonthly: 92.36,
    resaleMonthly: 96.98,
    refacturingRate: 700,
    refacturingUnit: "mois",
    refacturingTo: "",
  },
  {
    id: "TESLA-FERNANDO",
    type: "VHC Admin",
    brand: "TESLA Long Range — Fernando",
    plate: "VS 547 981",
    year: 2022,
    notes: "",
    lastExpertise: null,
    lastService: null,
    purchasePrice: 59630,
    company: "MBA Services",
    billedToMBAS: 0,
    leasingMonthly: 1140.95,
    leasingNumber: "4533824 / ZH",
    leasingEnd: "2026-06-30",
    insuranceMonthly: 102.27,
    resaleMonthly: 1305.38,
    refacturingRate: 1250,
    refacturingUnit: "mois",
    refacturingTo: "MBA C (70%) / ASV C (10%) / ASV CG (20%)",
  },
  {
    id: "TESLA-GERALD",
    type: "VHC Admin",
    brand: "TESLA 3 — Gérald",
    plate: "VS 505 751",
    year: 2022,
    notes: "",
    lastExpertise: null,
    lastService: null,
    purchasePrice: 48180,
    company: "MBA Services",
    billedToMBAS: 0,
    leasingMonthly: 805.65,
    leasingNumber: "RN117756612 / Leaseteq",
    leasingEnd: "2026-08-31",
    insuranceMonthly: 95.02,
    resaleMonthly: 945.70,
    refacturingRate: 1250,
    refacturingUnit: "mois",
    refacturingTo: "MBA",
  },
  {
    id: "TESLA-DEBOUT",
    type: "VHC Admin",
    brand: "TESLA 3 — Debout",
    plate: "VS 555 759",
    year: 2023,
    notes: "",
    lastExpertise: null,
    lastService: null,
    purchasePrice: 46980,
    company: "MBA Services",
    billedToMBAS: 0,
    leasingMonthly: 770.75,
    leasingNumber: "RN118287188 / Leaseteq",
    leasingEnd: "2027-02-28",
    insuranceMonthly: 95.02,
    resaleMonthly: 909.06,
    refacturingRate: 1250,
    refacturingUnit: "mois",
    refacturingTo: "ASV Fenêtres et Portes",
  },
  {
    id: "TESLA-MODEL-S",
    type: "VHC Admin",
    brand: "TESLA Model S Plaid — Giovanni",
    plate: "VS 33339",
    year: 2023,
    notes: "Plaques interchangeables avec Alfa Roméo",
    lastExpertise: null,
    lastService: null,
    purchasePrice: 102430,
    company: "MBA Services",
    billedToMBAS: 0,
    leasingMonthly: 1659.95,
    leasingNumber: "5000754 / ZH",
    leasingEnd: "2027-08-31",
    insuranceMonthly: 138.36,
    resaleMonthly: 1888.22,
    refacturingRate: 1750,
    refacturingUnit: "mois",
    refacturingTo: "MBA Immobilier SA",
  },
  {
    id: "TESLA-NUNES",
    type: "VHC Admin",
    brand: "TESLA 3 — Nunes",
    plate: "VS 556 501",
    year: 2023,
    notes: "",
    lastExpertise: null,
    lastService: null,
    purchasePrice: 45980,
    company: "MBA Services",
    billedToMBAS: 0,
    leasingMonthly: 457.40,
    leasingNumber: "RN118293876 / Leaseteq",
    leasingEnd: "2027-02-28",
    insuranceMonthly: 102.27,
    resaleMonthly: 587.65,
    refacturingRate: 1250,
    refacturingUnit: "mois",
    refacturingTo: "ASV Fenêtres et Portes",
  },
  {
    id: "TESLA-COQUOZ",
    type: "VHC Admin",
    brand: "TESLA 3 — Coquoz",
    plate: "VS 524 223",
    year: 2022,
    notes: "",
    lastExpertise: null,
    lastService: null,
    purchasePrice: 48680,
    company: "MBA Services",
    billedToMBAS: 0,
    leasingMonthly: 593.00,
    leasingNumber: "RN117750827 / Leaseteq",
    leasingEnd: "2026-08-31",
    insuranceMonthly: 95.02,
    resaleMonthly: 722.42,
    refacturingRate: 1250,
    refacturingUnit: "mois",
    refacturingTo: "ASV Fenêtres et Portes",
  },
  {
    id: "TESLA-VALENTIN",
    type: "VHC Admin",
    brand: "TESLA 3 — Valentin",
    plate: "VS 556 600",
    year: 2023,
    notes: "",
    lastExpertise: null,
    lastService: null,
    purchasePrice: 47180,
    company: "MBA Services",
    billedToMBAS: 0,
    leasingMonthly: 797.75,
    leasingNumber: "RN118683655 / Leaseteq",
    leasingEnd: "2027-02-28",
    insuranceMonthly: 95.02,
    resaleMonthly: 937.41,
    refacturingRate: 1250,
    refacturingUnit: "mois",
    refacturingTo: "",
  },

  // ── Machines ──────────────────────────────────────────────────────────────────
  {
    id: "M4",
    type: "Machines",
    brand: "Komatsu WA 95-3 (TRAX)",
    plate: "VS 1878",
    year: 2004,
    notes: "",
    lastExpertise: null,
    lastService: null,
    purchasePrice: 83928,
    company: "MBA Construction",
    billedToMBAS: 0,
    leasingMonthly: 0,
    leasingNumber: null,
    leasingEnd: null,
    insuranceMonthly: 26.62,
    resaleMonthly: 27.95,
    refacturingRate: 130,
    refacturingUnit: "jours",
    refacturingTo: "MBA",
  },
  {
    id: "M5",
    type: "Machines",
    brand: "Wacker Dumper 4001",
    plate: "VS 356 178",
    year: 2010,
    notes: "",
    lastExpertise: null,
    lastService: null,
    purchasePrice: 52724,
    company: "MBA Construction",
    billedToMBAS: 0,
    leasingMonthly: 0,
    leasingNumber: null,
    leasingEnd: null,
    insuranceMonthly: 9.33,
    resaleMonthly: 9.79,
    refacturingRate: 90,
    refacturingUnit: "jours",
    refacturingTo: "MBA",
  },
  {
    id: "M9",
    type: "Machines",
    brand: "Rétro Wacker ET 90",
    plate: null,
    year: 2018,
    notes: "",
    lastExpertise: null,
    lastService: "2020-11-11",
    purchasePrice: 86160,
    company: "MBA Construction",
    billedToMBAS: 0,
    leasingMonthly: 0,
    leasingNumber: null,
    leasingEnd: null,
    insuranceMonthly: 0,
    resaleMonthly: 0,
    refacturingRate: 150,
    refacturingUnit: "jours",
    refacturingTo: "MBA",
  },
  {
    id: "M10",
    type: "Machines",
    brand: "Pelle Liebherr R 914",
    plate: null,
    year: 2016,
    notes: "",
    lastExpertise: null,
    lastService: "2020-10-01",
    purchasePrice: 150120,
    company: "MBA Construction",
    billedToMBAS: 0,
    leasingMonthly: 0,
    leasingNumber: null,
    leasingEnd: null,
    insuranceMonthly: 0,
    resaleMonthly: 0,
    refacturingRate: 190,
    refacturingUnit: "jours",
    refacturingTo: "MBA",
  },
  {
    id: "M13",
    type: "Machines",
    brand: "Rétro Wacker EZ26",
    plate: null,
    year: 2023,
    notes: "service 22-23.09.2025: vidange, filtres, courroie, graissage",
    lastExpertise: null,
    lastService: "2025-09-23",
    purchasePrice: 53900,
    company: "MBA Services",
    billedToMBAS: 0,
    leasingMonthly: 0,
    leasingNumber: null,
    leasingEnd: null,
    insuranceMonthly: 0,
    resaleMonthly: 0,
    refacturingRate: 90,
    refacturingUnit: "jours",
    refacturingTo: "MBA",
  },
  {
    id: "M3",
    type: "Machines",
    brand: "Rétro Wacker EZ26",
    plate: null,
    year: 2021,
    notes: "",
    lastExpertise: null,
    lastService: null,
    purchasePrice: 45000,
    company: "MBA Services",
    billedToMBAS: 0,
    leasingMonthly: 0,
    leasingNumber: null,
    leasingEnd: null,
    insuranceMonthly: 0,
    resaleMonthly: 0,
    refacturingRate: 90,
    refacturingUnit: "jours",
    refacturingTo: "MBA",
  },
  {
    id: "M14",
    type: "Machines",
    brand: "Rétro Wacker EZ17",
    plate: null,
    year: 2023,
    notes: "",
    lastExpertise: null,
    lastService: null,
    purchasePrice: 38125,
    company: "MBA Services",
    billedToMBAS: 0,
    leasingMonthly: 0,
    leasingNumber: null,
    leasingEnd: null,
    insuranceMonthly: 0,
    resaleMonthly: 0,
    refacturingRate: 90,
    refacturingUnit: "jours",
    refacturingTo: "MBA",
  },
  {
    id: "M1",
    type: "Machines",
    brand: "Elevateur",
    plate: null,
    year: 0,
    notes: "",
    lastExpertise: null,
    lastService: null,
    purchasePrice: 0,
    company: "",
    billedToMBAS: 0,
    leasingMonthly: 0,
    leasingNumber: null,
    leasingEnd: null,
    insuranceMonthly: 0,
    resaleMonthly: 0,
    refacturingRate: 0,
    refacturingUnit: "",
    refacturingTo: "",
  },
  {
    id: "M8",
    type: "Machines",
    brand: "Bob-Cat T190 à Chenilles",
    plate: null,
    year: 2009,
    notes: "",
    lastExpertise: null,
    lastService: null,
    purchasePrice: 16140,
    company: "MBA Construction",
    billedToMBAS: 0,
    leasingMonthly: 0,
    leasingNumber: null,
    leasingEnd: null,
    insuranceMonthly: 0,
    resaleMonthly: 0,
    refacturingRate: 60,
    refacturingUnit: "jours",
    refacturingTo: "MBA",
  },
  {
    id: "G2",
    type: "Machines",
    brand: "Grue Schaller Terex Comedil 24+ (G2)",
    plate: null,
    year: 2010,
    notes: "G9210002",
    lastExpertise: null,
    lastService: null,
    purchasePrice: 86080,
    company: "MBA Construction",
    billedToMBAS: 0,
    leasingMonthly: 0,
    leasingNumber: null,
    leasingEnd: null,
    insuranceMonthly: 0,
    resaleMonthly: 0,
    refacturingRate: 2000,
    refacturingUnit: "mois",
    refacturingTo: "MBA",
  },
  {
    id: "G4",
    type: "Machines",
    brand: "Grue Schaller Terex Comedil 24+ (G4)",
    plate: null,
    year: 2013,
    notes: "G9211012",
    lastExpertise: null,
    lastService: null,
    purchasePrice: 65880,
    company: "MBA Construction",
    billedToMBAS: 0,
    leasingMonthly: 0,
    leasingNumber: null,
    leasingEnd: null,
    insuranceMonthly: 0,
    resaleMonthly: 0,
    refacturingRate: 2000,
    refacturingUnit: "mois",
    refacturingTo: "MBA",
  },
  {
    id: "G1",
    type: "Machines",
    brand: "Grue Schaller Terex Comedil 24+ (G1)",
    plate: null,
    year: 2019,
    notes: "G9219012",
    lastExpertise: null,
    lastService: null,
    purchasePrice: 78621,
    company: "MBA Construction",
    billedToMBAS: 0,
    leasingMonthly: 0,
    leasingNumber: null,
    leasingEnd: null,
    insuranceMonthly: 0,
    resaleMonthly: 0,
    refacturingRate: 2000,
    refacturingUnit: "mois",
    refacturingTo: "MBA",
  },
  {
    id: "G3",
    type: "Machines",
    brand: "Grue Benazzato (G3)",
    plate: null,
    year: 2005,
    notes: "",
    lastExpertise: "2023-06-16",
    lastService: null,
    purchasePrice: 110828,
    company: "MBA Construction",
    billedToMBAS: 0,
    leasingMonthly: 0,
    leasingNumber: null,
    leasingEnd: null,
    insuranceMonthly: 0,
    resaleMonthly: 0,
    refacturingRate: 2000,
    refacturingUnit: "mois",
    refacturingTo: "MBA",
  },
  {
    id: "ESSIEU-G",
    type: "Machines",
    brand: "Essieu grue GSST5006-2017CH",
    plate: "VS 8157",
    year: 2020,
    notes: "",
    lastExpertise: null,
    lastService: null,
    purchasePrice: 0,
    company: "MBA Construction",
    billedToMBAS: 0,
    leasingMonthly: 0,
    leasingNumber: null,
    leasingEnd: null,
    insuranceMonthly: 0,
    resaleMonthly: 0,
    refacturingRate: 0,
    refacturingUnit: "",
    refacturingTo: "",
  },
];
